#!/bin/bash

if [[ -z "$NODE_ENV" ]]; then
  echo enter NODE_ENV
  read NODE_ENV
  export NODE_ENV=$NODE_ENV
fi

if [[ -z "$VAULT_USER" ]]; then
  echo enter VAULT_USER
  read VAULT_USER
  export VAULT_USER=$VAULT_USER
fi

if [[ -z "$VAULT_PASS" ]]; then
  echo enter VAULT_PASS
  read -s VAULT_PASS
  export VAULT_PASS=$VAULT_PASS
fi

node config.js
