#!/bin/bash

set -e

if [[ -f ~/.vault-token ]]; then
  node scripts/config.js
  exit 0
fi

if [[ -z "$NODE_ENV" ]]; then
  read -p "enter NODE_ENV: " NODE_ENV
  export NODE_ENV=$NODE_ENV
fi

if [[ -z "$VAULT_USER" ]]; then
  read -p "enter VAULT_USER: " VAULT_USER
  export VAULT_USER=$VAULT_USER
fi

if [[ -z "$VAULT_PASS" ]]; then
  read -p "enter VAULT_PASS: " -s VAULT_PASS
  export VAULT_PASS=$VAULT_PASS
fi

node scripts/config.js
