name: Deploy

on:
  push:
    branches: ["master", "main", "devops/*"]
  workflow_dispatch:
    inputs:
      Environment:
        description: environment to deploy (dev, qa, stage, sandbox, test, prod)
        default: dev
        required: true
      Pipeline:
        description: pipeline to run
        default: build-execute
        required: true
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        run: |
          bash ./devops/scripts/runpipeline.sh
        env:
          ENV: ${{ github.event.inputs.Environment }}
          PIPELINE: ${{ github.event.inputs.Pipeline }}
